#!/bin/dash

HEREDIR="$(dirname "$(readlink -f "$0")")"

testifterminal_func () {
    case $(ps -o stat= -p $$) in
        *+*)
            echo "continue..."
            sleep 1
            ;;
        *)
            notify-send -t 900 "clean exit" "please run the command in terminal."
            exit 0
            ;;
    esac
}

case "$1" in
    ""|statusboard)
        "$HEREDIR"/statusboard/maintoggle
        ;;
    das|dicandsearch)
        "$HEREDIR"/taskmenu/dicandsearch
        ;;
    tsm|taskscriptmenu)
        "$HEREDIR"/taskmenu/taskscriptmenu
        ;;
    dro|directopen)
        "$HEREDIR"/taskmenu/directopen "$2"
        ;;
    mkd|makedirectopen)
        "$HEREDIR"/taskmenu/helpers/makedirectopen "$2"
        ;;
    ssm|screenshotmenu)
        "$HEREDIR"/taskmenu/screenshotmenu
        ;;
    bao|browseandopen)
        "$HEREDIR"/taskmenu/browseandopen "$2"
        ;;
    bnc|batnoticontrol)
        "$HEREDIR"/others/battnoticontrol "$2"
        ;;
    adc|audiocontrol)
        "$HEREDIR"/others/audiocontrol "$2"
        ;;
    scc|screencontrol)
        "$HEREDIR"/others/screencontrol "$2"
        ;;
    css|clipboardss)
        "$HEREDIR"/taskmenu/screenshots/clipboard-ss-Selected-Rectangle
        ;;
    sss|swappyss)
        "$HEREDIR"/taskmenu/screenshots/swappy-ss-Selected-Rectangle
        ;;
    sav|selectandview)
        "$HEREDIR"/selectedview/selectandview
        ;;
    pass|password)
        "$HEREDIR"/taskmenu/taskscripts/Passwords
        ;;
    kill)
        "$HEREDIR"/others/kill "$2"
        ;;
    mur|mshaur)
        "$HEREDIR"/others/mur "$2" "$3"
        ;;
    wifi|mshwifi)
        "$HEREDIR"/others/wificontrol
        ;;
    ecf|ecpfs)
        "$HEREDIR"/others/ecpfs "$2" "$3"
        ;;
    nsc|newscript)
        "$HEREDIR"/others/newscript "$2" "$3"
        ;;
    ext|extmonitor)
        "$HEREDIR"/others/extmonitor
        ;;
    ytd|ytdl)
        "$HEREDIR"/others/fzytdl "$2"
        ;;
    h|help)
        testifterminal_func
        cat "$HEREDIR"/iimanual
        exit 0
        ;;
    *)
        testifterminal_func
        cat "$HEREDIR"/iimanual
        exit 0
        ;;
esac
