#!/bin/dash

fdir="$(dirname "$(readlink -f "$0")")"
bdir="$(dirname "$fdir")"

while true; do
    open=$(ls "$bdir"/mndicsrc | wofi -d)
	if [ -d "$open" ]; then
		cd "$open"
	else
        if [ ! -z "$open" ]; then
            xdg-open "$bdir"/mndicsrc/"$open" &
        fi
		break
	fi
done
