#!/bin/dash

[ ! -z "$1" ] && cd "$1" > /dev/null 2>&1 || cd ~ > /dev/null 2>&1

while true; do
    open=$(ls -a --group-directories-first --file-type -- . | grep -v "^\.[a-zA-Z0-9]\|^\./" | bemenu -p "mshFM: ")
    if [ -d "$open" ]; then
        cd "$open"
    else
        if [ ! -z "$open" ]; then
            xdg-open "$open" &
        fi
        break
    fi
done
