#!/bin/dash
while true; do
    tfile=$(trash-list | bemenu -p "mshMenu: ")
    [ ! -z "$tfile" ] && tact=$(echo 'Restore\nDelete' | bemenu -p "mshMenu: ") || exit 0
    case $tact in
        Restore)
            foot -T "foot-float" -e trash-restore "$(echo "$tfile" | cut -d' ' -f3-)"
            ;;
        Delete)
            trash-rm "$(echo "$tfile" | cut -d' ' -f3-)"
            ;;
        *)
            exit 0
            ;;
    esac
done
