#!/bin/dash

passfiles=$(find ~/.password-store -name "*.gpg" | sed 's/\/home\/msh\/\.password-store\///;s/\.gpg//')

# selpassfile=$(echo "$passfiles" | bemenu -p "Passwords: ")
# selpassfile=$(echo "$passfiles" | wofi -d)

selpassfile=$(echo "$passfiles" | fuzzel -d) > /dev/null 2>&1
[ ! -z "$selpassfile" ] && pass show "$selpassfile" | wl-copy
