#!/bin/dash
notify-send -t 7000 "Default Audio Output (sink)" "$(pactl get-default-sink)"
sel=$(pactl list short sinks | cut -f2 | fuzzel -d) > /dev/null 2>&1
[ ! -z "$sel" ] && pactl set-default-sink "$sel" && \
    notify-send -t 7000 "Default Audio Output (sink)" "$(pactl get-default-sink)"
