#!/bin/dash
while true; do
    tfile=$(trash-list | fuzzel -d) > /dev/null 2>&1
    [ ! -z "$tfile" ] && tact=$(echo 'Restore\nDelete' | fuzzel -d) > /dev/null 2>&1 || exit 0
    case $tact in
        Restore)
            foot -T "foot-float" -e trash-restore "$(echo "$tfile" | cut -d' ' -f3-)"
            ;;
        Delete)
            trash-rm "$(echo "$tfile" | cut -d' ' -f3-)"
            ;;
        *)
            exit 0
            ;;
    esac
done
