#!/bin/dash

SCRIPTNAME="$(basename -- "$0")"
if pidof -x "$SCRIPTNAME" -o $$ >> /dev/null 2>&1; then
    notify-send -t 9000 "Already Running" "The batteryloop is already running. So, clean exit."
    exit 0
fi

HEREDIR="$(dirname "$(readlink -f "$0")")"

while true; do
    BATTSTATUS=$(cat /sys/class/power_supply/BAT0/status)
    BATTCAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
    echo "BAT: "$BATTSTATUS" "$BATTCAPACITY"%" > $HEREDIR/iwaited/battery
    sleep 20
    if ! pidof -x iwaitedloop > /dev/null 2>&1; then
        break
    fi
done & > /dev/null 2>&1
