#!/bin/dash

SCRIPTNAME="$(basename -- "$0")"
if pidof -x "$SCRIPTNAME" -o $$ >> /dev/null 2>&1; then
    notify-send -t 9000 "Already Running" "The batteryloop is already running. So, clean exit."
    exit 0
fi

HEREDIR="$(dirname "$(readlink -f "$0")")"

while true; do
    CONSTATE="$(cat /sys/class/net/wlo1/operstate)"
    WIFINAME="$(iwgetid -r)"
    IPADDRESS="$(ip addr show wlp0s20f3 | awk '/inet 192.168/ {print $2}')"
    echo "WiFi Connection: "$CONSTATE" | ESSID: "$WIFINAME" | IP Address: "$IPADDRESS"" > "$HEREDIR"/iwaited/wificonnection
    sleep 60
    if ! pidof -x iwaitedloop > /dev/null 2>&1; then
        break
    fi
done & > /dev/null 2>&1
