#!/bin/dash

HEREDIR="$(dirname "$(readlink -f "$0")")"
BACKDIR="$(dirname "$HEREDIR")"
MENU1=""$BACKDIR"/helpers/menumaker1"

CKPMU=$(mount | grep sda1)
if [ -z "$CKPMU" ]; then
    MSEL=$(echo "001HDD is NOT mounted, leave as it is\nMount 001HDD data partition" | "$MENU1")
    if [ "$MSEL" = "Mount 001HDD data partition" ]; then
        mkdir -p /home/msh/001HDD
        mount /home/msh/001HDD
        notify-send -t 1800 "Mounted" "/dev/sda1 is mounted to ~/001HDD"
    else
        notify-send -t 1800 "Leave" "/dev/sda1 is still UNMOUNTED to ~/001HDD"
    fi
else
    USEL=$(echo "001HDD is MOUNTED, leave as it is\nUnmount 001HDD data partition" | "$MENU1")
    if [ "$USEL" = "Unmount 001HDD data partition" ]; then
        CKBUSY=$(lsof /home/msh/001HDD)
        if [ -z "$CKBUSY" ]; then
            umount /home/msh/001HDD
            sleep 1s
            # rmdir ~/001HDD >>/dev/null 2>&1
            # notify-send -t 1800 "Unmounted" "/dev/sda1 is unmounted and ~/001HDD dir has been deleted"
            notify-send -t 1800 "Unmounted" "/dev/sda1 is unmounted."
        else
            notify-send -t 1800 "Device is busy. It cannot be unmounted." "$CKBUSY"
        fi
    else
        notify-send -t 1800 "Leave" "/dev/sda1 is still MOUNTED to ~/001HDD"
    fi
fi > /dev/null 2>&1
