#!/bin/dash

HEREDIR="$(dirname "$(readlink -f "$0")")"
BACKDIR="$(dirname "$HEREDIR")"
MENU1=""$BACKDIR"/helpers/menumaker1"

PASSFILES=$(find ~/.password-store -name "*.gpg" | sed 's/\/home\/msh\/\.password-store\///;s/\.gpg//')

SELPASSFILE=$(echo "$PASSFILES" | "$MENU1")

if [ -f ~/.password-store/"$SELPASSFILE".gpg ]; then
    pass show "$SELPASSFILE" | wl-copy
    notify-send -t 900 "successful" "your password has been copied to clipboard"
else
    notify-send -t 900 "clean exit" "empty or not exist."
fi
