#!/bin/dash

if [ "$XDG_CURRENT_DESKTOP" != "sway" ]; then
    notify-send -t 900 "clean exit" "sway is not running."
    exit 0
fi

grim -g "$(swaymsg -t get_tree | jq -j '.. | select(.type?) | select(.focused).rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | swappy -f -
notify-send -t 900 \
    "Focused Window Screenshot" \
    "A screenshot of your focused window has been opened and edited in swappy."
